export const BASE_API_ROUTE_V1 = "/api";

export const INCOMING_STOCK_COLLECTION_NAME = "INCOMING_STOCK"
export const STOCK_IN_COLLECTION_NAME = "STOCK_IN"
export const INSPECTION_COLLECTION_NAME = "INSPECTIONS"
export const PUT_AWAY_COLLECTION_NAME = "PUT_AWAY"
export const WAREHOUSE_COLLECTION_NAME = "WAREHOUSE"
export const PICKING_LIST_COLLECTION_NAME = "PICKING_LISTS"
export const STOCK_OUT_COLLECTION_NAME = "STOCK_OUT"
export const DISPATCHED_COLLECTION_NAME = "DISPATCHED"